sudo: required
language: go
services:
  - docker
go:
 - 1.6.1
 - 1.7.1
script:
  - go get gopkg.in/yaml.v2
  - go get github.com/stretchr/testify/assert
  - go test -v
  - go build -o codeci
  - ./codeci --version
  - ./codeci --help
  - ./codeci test
  - ./codeci 